### ISSUE TITLE
Pollutes sous-chefs/ruby_rbenv `RBENV_ROOT`

### ISSUE THREAD

**Issue by hedgehog** [darwin67/chef-pyenv#36]
Thanks for porting the rbenv cookbook.  Not sure where responsibility lies - opening here since rbenv cookbook seems to have priority.

### Cookbook version
`3.1.0`

### Chef-client version
`14.13.11`

### Platform Details
```
localhost         platform=ubuntu
localhost         platform_version=18.04
localhost         ruby=ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
```

### Scenario:
Manage Python using this cookbook.
Manage Ruby using [sous-chefs/ruby_rbenv](https://github.com/sous-chefs/ruby_rbenv)

### Steps to Reproduce:
Include user install recipe from `chef-pyenv/test/fixtures/cookbooks/test/recipes/user_install.rb ` 
Include user install recipe from `sous-chefs/ruby_rbenv/test/fixtures/cookbooks/test/recipes/user_install.rb`

### Expected Result:
Installs proceed.

### Actual Result:
Ruby install fails with `"RBENV_ROOT"=>"/home/hedge/.pyenv"` in the following:
```
localhost         Compiled Resource:
localhost         ------------------
localhost         # Declared in /var/chef/cache/coolocalhost         Compiled Resource:
localhost         ------------------
localhost         # Declared in /var/chef/cache/cookbooks/ruby_rbenv/resources/script.rb:39:in `block in class_from_file'
localhost         
localhost         bash("rbenv install 2.5.5 (hedge)") do
localhost           action [:run]
localhost           default_guard_interpreter :default
localhost           command nil
localhost           backup 5
localhost           interpreter "bash"
localhost           declared_type :bash
localhost           cookbook_name "desktop"
localhost           code "export RBENV_ROOT=\"/home/hedge/.pyenv\"\nexport PATH=\"${RBENV_ROOT}/bin:$PATH\"\neval \"$(rbenv init -)\"\nrbenv install 2.5.5\n"
localhost           environment {"RBENV_ROOT"=>"/home/hedge/.pyenv", "USER"=>"hedge", "HOME"=>"/home/hedge"}
localhost           domain nil
localhost         ------------
localhost         chef_version=14.13.11
localhost         platform=ubuntu
localhost         platform_version=18.04
localhost         ruby=ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
localhost         program_name=/usr/bin/chef-client
localhost         executable=/opt/chef/bin/chef-client
kbooks/ruby_rbenv/resources/script.rb:39:in `block in class_from_file'
localhost         
localhost         bash("rbenv install 2.5.5 (hedge)") do
localhost           action [:run]
localhost           default_guard_interpreter :default
localhost           command nil
localhost           backup 5
localhost           interpreter "bash"
localhost           declared_type :bash
localhost           cookbook_name "desktop"
localhost           code "export RBENV_ROOT=\"/home/hedge/.pyenv\"\nexport PATH=\"${RBENV_ROOT}/bin:$PATH\"\neval \"$(rbenv init -)\"\nrbenv install 2.5.5\n"
localhost           environment {"RBENV_ROOT"=>"/home/hedge/.pyenv", "USER"=>"hedge", "HOME"=>"/home/hedge"}
localhost           domain nil
localhost         ------------
localhost         chef_version=14.13.11
localhost         platform=ubuntu
localhost         platform_version=18.04
localhost         ruby=ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
localhost         program_name=/usr/bin/chef-client
localhost         executable=/opt/chef/bin/chef-client
```

**Comment by darwin67** [comment]
Hey, thank you for reporting.

Unfortunately, I'm unable to reproduce this.

In the following environment,
**OS:** Ubuntu 18.04 (Virtualbox)
**Chef:** 14.13.11

I've tried something like this, which is what you have for your scenario, and I've also tried what you said by running the test recipes and I don't get the similar errors.
All I get are the `libssl` incompatible errors which are already acknowledged.
```
#
# Cookbook:: test
# Recipe:: default
#
# Copyright:: 2019, The Authors, All Rights Reserved.

apt_update 'update'

user = 'vagrant'
python_version = '3.7.0'
ruby_version = '2.5.5'

pyenv_user_install user
pyenv_python python_version do
  user user
end

pyenv_global python_version do
  user user
end

rbenv_user_install user
rbenv_ruby ruby_version do
  user user
end

rbenv_global ruby_version do
  user user
end
```

If you can provide a test cookbook that reproduces what you are seeing, that would make it easier for me to look into it.
